title: Will Kitch Blog
description: >-
  Welcome to my side of the internet!
author:
  name: Will Kitch
  email: will@willkitch.me

url: https://blog.willkitch.me

theme: minima

minima:
  skin: solarized-dark
  nav_pages:
    - about.md
  show_excerpts: false
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/glimmercharger
